name: mu
description: "Mu"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.68.0
  flutter_tts: ^3.8.3
  intl: ^0.20.2
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.8
  video_player: ^2.8.1
  http: ^1.1.0
  just_audio: ^0.9.36
  path_provider: ^2.1.5
  lottie: ^2.2.0
  image_picker: ^0.8.9
  image: ^3.0.1
  tflite_flutter: ^0.11.0
  camera: ^0.11.0+2
  audioplayers: ^6.0.0
  permission_handler: ^12.0.1
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path: ^1.9.1
  flutter_slidable: ^4.0.3
  flutter_svg: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/mainimg.jpg
    - assets/box.jpg
    - assets/empty.jpg
    - assets/fill.jpg
    - assets/motion.gif
    - assets/gradient/gradient.png
    - assets/gradient/gradient_gam.png
    - assets/gradient/gradient_mol.png
    - assets/HourGlass.json
    - .env
    - assets/detect.tflite
    - assets/1.tflite
    - assets/labelmap.txt
    - assets/popup.png
    - assets/roadingyou.png
    - assets/test/test1.png
    - assets/test/test2.png
    - assets/test/test3.png
    - assets/test/test4.png
    - assets/test/test5.png
    - assets/test/test6.png
    - assets/test/test7.png
    - assets/test/test8.png
    - assets/test/test9.png
    - assets/test/test10.png
    - assets/test/test_ba.png
    - assets/test/test_mo.png
    - assets/test/test_ga.png
    - assets/test/card_background.png
    - assets/home/mom_bang.png
    - assets/home/mom_gam.png
    - assets/home/mom_mol.png
    - assets/home/retest_bang.png
    - assets/home/retest_gam.png
    - assets/home/retest_mol.png
    - assets/home/refr.png
    - assets/home/closet.png
    - assets/home/drawer.png
    - assets/home/refr_lock.png
    - assets/home/closet_lock.png
    - assets/home/drawer_lock.png
    - assets/my/right_arrow.png
    - assets/my/mymom_bang.png
    - assets/my/ex.png
    - assets/my/mymom_gam.png
    - assets/my/mymom_mol.png
    - assets/my/clover.png
    - assets/main_box.png
    - assets/my/re0.png
    - assets/my/re1.png
    - assets/my/re2.png
    - assets/my/re3.png
    - assets/my/dr0.png
    - assets/my/dr1.png
    - assets/my/dr2.png
    - assets/my/dr3.png
    - assets/my/cl0.png
    - assets/my/cl1.png
    - assets/my/cl2.png
    - assets/my/cl3.png
    - assets/my/cl4.png
    - assets/my/idea.png
    - assets/home/lock.png
    - assets/bottom_icons/home_unselected.svg
    - assets/bottom_icons/home_selected.svg
    - assets/bottom_icons/mission_unselected.svg
    - assets/bottom_icons/mission_selected.svg
    - assets/bottom_icons/my_unselected.svg
    - assets/bottom_icons/my_selected.svg
    - assets/left.svg
    - assets/home/categorybox.png
    - assets/mission/still_cl.png
    - assets/mission/still_dr.png
    - assets/mission/still_re.png
    - assets/mission/loading_re.mp4
    - assets/mission/loading_cl.mp4
    - assets/mission/loading_dr.mp4
    - assets/mission/delete.svg
    - assets/mission/edit.svg
    - assets/mission/pause.svg
    - assets/mission/plus.svg
    - assets/mission/sound_on.svg
    - assets/mission/mission_dr.png
    - assets/mission/mission_cl.png
    - assets/mission/mission_re.png


  fonts:

    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf